// Helpers shared between the two fractions modules.
// Items are generated by enumeration so the question bank is deterministic
// (no Math.random at module-load time) and easy to unit-test.

export const FRACTION_LEVELS = [1, 2, 3] as const;
export type FractionLevel = (typeof FRACTION_LEVELS)[number];

// Configurable target — modules may override per-level via their own constant.
export const QUESTIONS_PER_LEVEL = 25;

// How many items the test generator samples by default. Spec calls for 5 but
// it might change — modules read this through ContentModule.defaultTestSize.
export const DEFAULT_TEST_SIZE = 5;

export function gcd(a: number, b: number): number {
  a = Math.abs(a);
  b = Math.abs(b);
  while (b !== 0) {
    [a, b] = [b, a % b];
  }
  return a;
}

/**
 * Deterministic pseudo-shuffle so we can pick a stable sample of size N from
 * a larger enumeration without using Math.random at module-load time.
 *
 * The seed is XOR-mixed with each index so different seeds genuinely re-order
 * the list (a constant offset would leave ordering unchanged).
 */
export function pickN<T>(list: T[], n: number, seed: number): T[] {
  if (list.length <= n) return list.slice();
  const indexed = list.map((value, i) => ({
    value,
    key: (((i + 1) * 2654435761) ^ ((seed + 1) * 1597334677)) >>> 0,
  }));
  indexed.sort((a, b) => a.key - b.key);
  return indexed.slice(0, n).map((x) => x.value);
}
