// Question bank for "Powstanie kościuszkowskie i rozbiory Polski" (4th-grade
// history). Three topics share one bank — the modules filter by `topic`.
//
//   CRISIS    — Kryzys Rzeczypospolitej, I i II rozbiór, Konstytucja 3 maja
//   UPRISING  — Powstanie kościuszkowskie (przysięga, Racławice, Maciejowice)
//   AFTERMATH — III rozbiór, utrata niepodległości, Panorama Racławicka
//
// Each level-bucket holds enough items for a 10-question random test.

import type { ContentItem } from '../types';

export type KosciuszkoRozbioryTopic = 'CRISIS' | 'UPRISING' | 'AFTERMATH';

export const KOSCIUSZKO_ROZBIORY_LEVELS = [1, 2, 3] as const;
export type KosciuszkoRozbioryLevel =
  (typeof KOSCIUSZKO_ROZBIORY_LEVELS)[number];

export const KOSCIUSZKO_ROZBIORY_TEST_SIZE = 10;

let nextSeq = 0;
function q(
  level: KosciuszkoRozbioryLevel,
  topic: KosciuszkoRozbioryTopic,
  prompt: string,
  options: string[],
  answer: string,
  hint?: string
): ContentItem {
  nextSeq += 1;
  const id = `kosciuszko-rozbiory-${String(nextSeq).padStart(3, '0')}`;
  return {
    id,
    type: 'SINGLE_CHOICE',
    level,
    topic,
    content: {
      prompt: { pl: prompt },
      options: { pl: options },
      answer: { pl: answer },
      ...(hint ? { hint: { pl: hint } } : {}),
    },
  };
}

const items: ContentItem[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // CRISIS — Kryzys Rzeczypospolitej, I i II rozbiór, Konstytucja 3 maja
  // ───────────────────────────────────────────────────────────────────────────

  // ── CRISIS · Level 1 (basic recall) ───────────────────────────────────────
  q(1, 'CRISIS', 'W którym wieku pogłębiał się kryzys Rzeczypospolitej?',
    ['W XVI wieku', 'W XVII wieku', 'W XVIII wieku', 'W XIX wieku'],
    'W XVIII wieku',
    'To samo stulecie, w którym uchwalono Konstytucję 3 maja.'),
  q(1, 'CRISIS', 'Jak miał na imię ostatni król Polski przed rozbiorami?',
    ['Stanisław August Poniatowski', 'Jan III Sobieski', 'Władysław Jagiełło', 'August III Sas'],
    'Stanisław August Poniatowski'),
  q(1, 'CRISIS', 'Ile państw dokonało rozbiorów Polski?',
    ['Dwa', 'Trzy', 'Cztery', 'Pięć'],
    'Trzy',
    'Rosja, Prusy i Austria.'),
  q(1, 'CRISIS', 'W którym roku uchwalono Konstytucję 3 maja?',
    ['1772', '1791', '1793', '1795'],
    '1791'),
  q(1, 'CRISIS', 'Jak nazywała się pierwsza polska konstytucja?',
    ['Konstytucja 3 maja', 'Konstytucja 11 listopada', 'Konstytucja kwietniowa', 'Konstytucja PRL'],
    'Konstytucja 3 maja'),
  q(1, 'CRISIS', 'Które z państw NIE było zaborcą Polski?',
    ['Francja', 'Rosja', 'Prusy', 'Austria'],
    'Francja'),
  q(1, 'CRISIS', 'Czy Konstytucja 3 maja była pierwszym takim dokumentem w Europie?',
    ['Tak, była pierwszą konstytucją w Europie', 'Nie, była dwudziesta', 'Nie, była dziesiąta w Europie', 'Nie, w Europie były już cztery konstytucje'],
    'Tak, była pierwszą konstytucją w Europie'),
  q(1, 'CRISIS', 'W którym miesiącu uchwalono Konstytucję 3 maja?',
    ['W marcu', 'W maju', 'W lipcu', 'W listopadzie'],
    'W maju',
    'Podpowiedź jest w samej nazwie konstytucji.'),
  q(1, 'CRISIS', 'Które państwo na zachodzie sąsiadowało z Polską i było zaborcą?',
    ['Francja', 'Hiszpania', 'Prusy', 'Holandia'],
    'Prusy'),
  q(1, 'CRISIS', 'Które państwo na wschodzie sąsiadowało z Polską i było zaborcą?',
    ['Turcja', 'Szwecja', 'Włochy', 'Rosja'],
    'Rosja'),
  q(1, 'CRISIS', 'Czy król Stanisław August próbował przeprowadzać reformy?',
    ['Tak, próbował', 'Nie, niczego nie próbował zmienić', 'Reformy dotyczyły tylko sztuki', 'Tylko po III rozbiorze'],
    'Tak, próbował'),
  q(1, 'CRISIS', 'Czy reformy króla Stanisława Augusta zatrzymały kryzys państwa?',
    ['Tak, kryzys minął całkowicie', 'Tak, na sto lat', 'Nie, nie udało się go zatrzymać', 'Reform nie było w ogóle'],
    'Nie, nie udało się go zatrzymać'),
  q(1, 'CRISIS', 'Ile rozbiorów Polski było przed wybuchem powstania kościuszkowskiego?',
    ['Żaden', 'Jeden', 'Dwa', 'Trzy'],
    'Dwa',
    'I rozbiór w 1772 r. i II rozbiór w 1793 r.'),
  q(1, 'CRISIS', 'Co znaczy słowo „rozbiór" w odniesieniu do Polski?',
    ['Podział ziem Polski między obce państwa', 'Rozebranie zamku królewskiego', 'Rozliczenie podatków w Sejmie', 'Wydanie pierwszej konstytucji'],
    'Podział ziem Polski między obce państwa'),
  q(1, 'CRISIS', 'Który malarz namalował obraz „Pochód twórców Konstytucji 3 maja"?',
    ['Jan Matejko', 'Wojciech Kossak', 'Jan Styka', 'Stanisław Wyspiański'],
    'Jan Matejko'),
  q(1, 'CRISIS', 'Po ilu latach od Konstytucji 3 maja Rosja i Prusy dokonały kolejnego rozbioru?',
    ['W tym samym roku', 'Po dwóch latach', 'Po pięciu latach', 'Po dziesięciu latach'],
    'Po dwóch latach',
    '1791 + 2 = 1793.'),
  q(1, 'CRISIS', 'Kim był Stanisław Małachowski?',
    ['Marszałkiem Sejmu', 'Carem Rosji', 'Królem Prus', 'Cesarzem Austrii'],
    'Marszałkiem Sejmu'),
  q(1, 'CRISIS', 'Co unosi marszałek Stanisław Małachowski na obrazie Matejki?',
    ['Tekst Konstytucji 3 maja', 'Sztandar Rzeczypospolitej', 'Berło królewskie', 'Mapę Polski'],
    'Tekst Konstytucji 3 maja'),
  q(1, 'CRISIS', 'Czy państwa sąsiadujące z Polską miały silne armie?',
    ['Tak, miały silne armie', 'Nie, były słabsze niż Polska', 'Tylko Austria miała wojsko', 'Żadne nie miało armii'],
    'Tak, miały silne armie'),
  q(1, 'CRISIS', 'Jakimi ulicami biegnie pochód twórców konstytucji na obrazie Matejki?',
    ['Ulicami Warszawy', 'Ulicami Krakowa', 'Ulicami Wilna', 'Ulicami Poznania'],
    'Ulicami Warszawy'),
  q(1, 'CRISIS', 'W którym roku Jan Matejko namalował „Pochód twórców Konstytucji 3 maja"?',
    ['1791', '1830', '1891', '1918'],
    '1891',
    'Sto lat po uchwaleniu konstytucji.'),
  q(1, 'CRISIS', 'Który z zaborców leżał na południe od Polski?',
    ['Rosja', 'Prusy', 'Austria', 'Szwecja'],
    'Austria'),

  // ── CRISIS · Level 2 (intermediate) ───────────────────────────────────────
  q(2, 'CRISIS', 'W którym roku doszło do I rozbioru Polski?',
    ['1772', '1791', '1793', '1795'],
    '1772'),
  q(2, 'CRISIS', 'W którym roku doszło do II rozbioru Polski?',
    ['1772', '1791', '1793', '1795'],
    '1793'),
  q(2, 'CRISIS', 'Które dwa państwa dokonały II rozbioru Polski?',
    ['Rosja i Austria', 'Prusy i Austria', 'Rosja i Prusy', 'Francja i Rosja'],
    'Rosja i Prusy',
    'Austria nie wzięła udziału w II rozbiorze.'),
  q(2, 'CRISIS', 'O ile zmniejszyła się Rzeczpospolita po II rozbiorze?',
    ['O ponad połowę powierzchni', 'Tylko o niewielki kawałek', 'W ogóle się nie zmniejszyła', 'Wszystko zostało zabrane'],
    'O ponad połowę powierzchni'),
  q(2, 'CRISIS', 'Od kogo był zależny król Polski po II rozbiorze?',
    ['Od króla Prus', 'Od cesarza Austrii', 'Od papieża', 'Od ambasadora rosyjskiego'],
    'Od ambasadora rosyjskiego'),
  q(2, 'CRISIS', 'Co miało zostać przywrócone według Konstytucji 3 maja w sprawie tronu?',
    ['Dziedziczność tronu', 'Wybór króla losowo', 'Władza Sejmu zamiast króla', 'Tron miał zostać zniesiony'],
    'Dziedziczność tronu'),
  q(2, 'CRISIS', 'Kogo prześladowano w Polsce po II rozbiorze?',
    ['Polskich patriotów', 'Wyłącznie kupców', 'Tylko obcokrajowców', 'Nikogo nie prześladowano'],
    'Polskich patriotów'),
  q(2, 'CRISIS', 'Co zakładała Konstytucja 3 maja w sprawie rządu?',
    ['Utworzenie rządu', 'Likwidację rządu', 'Tylko zmianę nazwy państwa', 'Wycofanie wojska z miast'],
    'Utworzenie rządu'),
  q(2, 'CRISIS', 'Co groziło Polsce po drugim rozbiorze?',
    ['Kolejny rozbiór ziem', 'Wojna z Anglią', 'Wybuch wulkanu', 'Klęska głodu'],
    'Kolejny rozbiór ziem'),
  q(2, 'CRISIS', 'Czy I rozbiór Polski nastąpił przed Konstytucją 3 maja?',
    ['Tak, dziewiętnaście lat wcześniej', 'Nie, dopiero po niej', 'W tym samym roku', 'Nigdy nie było I rozbioru'],
    'Tak, dziewiętnaście lat wcześniej',
    '1772 vs 1791.'),
  q(2, 'CRISIS', 'Czy II rozbiór Polski nastąpił po Konstytucji 3 maja?',
    ['Tak, dwa lata po jej uchwaleniu', 'Nie, przed nią', 'W tym samym roku co konstytucja', 'Nigdy nie nastąpił'],
    'Tak, dwa lata po jej uchwaleniu'),
  q(2, 'CRISIS', 'Które trzy państwa dokonały I rozbioru Polski?',
    ['Rosja, Prusy i Austria', 'Francja, Anglia i Rosja', 'Tylko Rosja', 'Szwecja, Prusy i Austria'],
    'Rosja, Prusy i Austria'),
  q(2, 'CRISIS', 'Co wyniszczyło Rzeczpospolitą w stuleciu poprzedzającym kryzys?',
    ['Liczne wojny', 'Wielka epidemia trądu', 'Brak opadów przez sto lat', 'Bunt mieszczan'],
    'Liczne wojny'),
  q(2, 'CRISIS', 'Z jakich powodów Polska była słaba w XVIII wieku?',
    ['Brakowało reform i była wyniszczona wcześniejszymi wojnami', 'Polska była wtedy najsilniejsza w Europie', 'Polacy nie mieli broni', 'Polska nie miała króla'],
    'Brakowało reform i była wyniszczona wcześniejszymi wojnami'),
  q(2, 'CRISIS', 'Kim na obrazie Matejki jest postać oznaczona numerem 1?',
    ['Król Stanisław August Poniatowski', 'Tadeusz Kościuszko', 'Jan III Sobieski', 'Wojciech Bartos'],
    'Król Stanisław August Poniatowski'),
  q(2, 'CRISIS', 'Kim na obrazie Matejki jest postać oznaczona numerem 2?',
    ['Marszałek Stanisław Małachowski', 'Tadeusz Kościuszko', 'Józef Poniatowski', 'Jan Henryk Dąbrowski'],
    'Marszałek Stanisław Małachowski'),
  q(2, 'CRISIS', 'Czy najważniejsze założenia Konstytucji 3 maja udało się wprowadzić w życie?',
    ['Nie', 'Tak, w pełni', 'Tylko w Krakowie', 'Konstytucji w ogóle nie spisano'],
    'Nie'),
  q(2, 'CRISIS', 'Czym była Konstytucja 3 maja dla państwa polskiego?',
    ['Próbą ratowania państwa', 'Tylko zwykłą ustawą o podatkach', 'Obrazem Matejki', 'Umową handlową z Rosją'],
    'Próbą ratowania państwa'),
  q(2, 'CRISIS', 'Po którym rozbiorze powierzchnia Rzeczypospolitej zmniejszyła się o ponad połowę?',
    ['Po I rozbiorze', 'Po II rozbiorze', 'Po III rozbiorze', 'Po IV rozbiorze'],
    'Po II rozbiorze'),
  q(2, 'CRISIS', 'Kto wpływał na wewnętrzne sprawy Polski w XVIII wieku?',
    ['Sąsiadujące państwa: Rosja, Prusy i Austria', 'Anglia i Francja', 'Szwecja i Turcja', 'Tylko Watykan'],
    'Sąsiadujące państwa: Rosja, Prusy i Austria'),
  q(2, 'CRISIS', 'Jak zachowywał się król Stanisław August wobec potrzeby reform?',
    ['Próbował je przeprowadzać', 'Nie zgadzał się na żadne zmiany', 'Zakazał reform całkowicie', 'Nigdy nie istniał taki król'],
    'Próbował je przeprowadzać'),
  q(2, 'CRISIS', 'Co — według założeń Konstytucji 3 maja — miał stworzyć ten dokument?',
    ['Sprawniejszy rząd i nowoczesne państwo', 'Nowe wojsko najemne', 'Prywatne folwarki dla króla', 'Imperium kolonialne'],
    'Sprawniejszy rząd i nowoczesne państwo'),

  // ── CRISIS · Level 3 (advanced) ───────────────────────────────────────────
  q(3, 'CRISIS', 'Który rozbiór miał miejsce w 1772 roku?',
    ['Pierwszy', 'Drugi', 'Trzeci', 'Czwarty'],
    'Pierwszy'),
  q(3, 'CRISIS', 'Który rozbiór miał miejsce w 1793 roku?',
    ['Pierwszy', 'Drugi', 'Trzeci', 'Czwarty'],
    'Drugi'),
  q(3, 'CRISIS', 'Co było głównym powodem upadku Rzeczypospolitej w XVIII wieku?',
    ['Wewnętrzny kryzys państwa i wzrost potęgi sąsiadów', 'Zaraza, która zabiła wszystkich mieszkańców', 'Trzęsienie ziemi w Warszawie', 'Brak ludności'],
    'Wewnętrzny kryzys państwa i wzrost potęgi sąsiadów'),
  q(3, 'CRISIS', 'Czy Konstytucja 3 maja była pierwszą konstytucją na świecie?',
    ['Nie, była pierwsza w Europie i druga na świecie', 'Tak, w ogóle pierwszą na świecie', 'Nie, była dziesiąta na świecie', 'Była dwudziesta na świecie'],
    'Nie, była pierwsza w Europie i druga na świecie',
    'Pierwsza na świecie była konstytucja Stanów Zjednoczonych.'),
  q(3, 'CRISIS', 'W jakiej epoce historycznej uchwalono Konstytucję 3 maja?',
    ['Starożytność', 'Średniowiecze', 'Nowożytność', 'Współczesność'],
    'Nowożytność',
    'XVIII wiek to nowożytność.'),
  q(3, 'CRISIS', 'Jakie lata obejmuje XVIII stulecie?',
    ['Lata 1601–1700', 'Lata 1701–1800', 'Lata 1801–1900', 'Lata 1901–2000'],
    'Lata 1701–1800'),
  q(3, 'CRISIS', 'Co znaczy słowo „kryzys" w odniesieniu do Rzeczypospolitej XVIII wieku?',
    ['Trudna sytuacja, słabość państwa', 'Obraz przedstawiający króla', 'Element konstytucji', 'Tytuł honorowy'],
    'Trudna sytuacja, słabość państwa'),
  q(3, 'CRISIS', 'Czy w 1791 roku Polska była niepodległa?',
    ['Tak, była jeszcze niepodległa', 'Nie, była już częścią Rosji', 'Nie, była częścią Prus', 'Nie istniała wtedy w ogóle'],
    'Tak, była jeszcze niepodległa',
    'II rozbiór nastąpił dopiero w 1793 r.'),
  q(3, 'CRISIS', 'Co stworzono w Polsce, aby uchronić państwo przed upadkiem?',
    ['Konstytucję 3 maja', 'Pierwszą szkołę', 'Pierwszy bank w Europie', 'Akademię Umiejętności'],
    'Konstytucję 3 maja'),
  q(3, 'CRISIS', 'Z którego stulecia pochodzą wszystkie trzy rozbiory Polski?',
    ['Z XVI wieku', 'Z XVII wieku', 'Z XVIII wieku', 'Z XIX wieku'],
    'Z XVIII wieku',
    '1772, 1793 i 1795.'),
  q(3, 'CRISIS', 'Czy obraz Matejki „Pochód twórców Konstytucji 3 maja" powstał za życia króla Stanisława Augusta?',
    ['Nie, prawie 100 lat po jego śmierci', 'Tak, król sam pozował do portretu', 'Tak, król zamówił go u Matejki', 'Tak, ale rok po jego śmierci'],
    'Nie, prawie 100 lat po jego śmierci',
    'Obraz powstał w 1891 r., a król zmarł w 1798 r.'),
  q(3, 'CRISIS', 'W którym sąsiadującym państwie panował car?',
    ['W Rosji', 'W Prusach', 'W Austrii', 'We Francji'],
    'W Rosji'),
  q(3, 'CRISIS', 'W którym sąsiadującym państwie panował król?',
    ['W Rosji', 'W Prusach', 'W Austrii', 'W Turcji'],
    'W Prusach'),
  q(3, 'CRISIS', 'W którym sąsiadującym państwie panował cesarz?',
    ['W Polsce', 'W Watykanie', 'W Holandii', 'W Austrii'],
    'W Austrii'),
  q(3, 'CRISIS', 'Co — mimo rozwoju kultury — przyniósł Polsce wiek XVIII?',
    ['Stopniowy upadek państwa', 'Złoty wiek bogactwa', 'Wzrost potęgi militarnej', 'Panowanie nad całą Europą'],
    'Stopniowy upadek państwa'),
  q(3, 'CRISIS', 'Co osłabiało Rzeczpospolitą jeszcze w XVII wieku, przed kryzysem XVIII wieku?',
    ['Liczne wyniszczające wojny', 'Brak ludności po wynalezieniu pisma', 'Wybór złego króla pod imieniem', 'Brak żywności po nieurodzaju w XX wieku'],
    'Liczne wyniszczające wojny'),
  q(3, 'CRISIS', 'Czy państwa sąsiednie wykorzystywały słabość Polski, aby wpływać na sprawy wewnętrzne?',
    ['Tak', 'Nie, były neutralne', 'Tylko Watykan ingerował', 'Polska była wtedy najsilniejszym państwem Europy'],
    'Tak'),
  q(3, 'CRISIS', 'Jak nazywano państwo polsko-litewskie w XVIII wieku?',
    ['Rzeczpospolita', 'Cesarstwo Polskie', 'Imperium Polskie', 'Republika Bałtycka'],
    'Rzeczpospolita',
    'Pełna nazwa: Rzeczpospolita Obojga Narodów.'),
  q(3, 'CRISIS', 'Czy król Stanisław August zasiadł na tronie z poparciem któregoś z sąsiadów?',
    ['Tak, z poparciem Rosji', 'Nie, sam zdobył tron mieczem', 'Tak, z poparciem Anglii', 'Tak, z poparciem Watykanu'],
    'Tak, z poparciem Rosji'),
  q(3, 'CRISIS', 'Jak długo trwał kryzys Rzeczypospolitej, który doprowadził do rozbiorów?',
    ['Cały XVIII wiek', 'Tylko jeden rok', 'Dwa miesiące', 'Sto lat, ale dopiero w XX wieku'],
    'Cały XVIII wiek'),
  q(3, 'CRISIS', 'Po I rozbiorze, jaką polityczną pozycję miała Polska wobec Rosji?',
    ['Była coraz bardziej zależna od Rosji', 'Była dla Rosji groźnym wrogiem', 'Sojuszniczo wspólnie podbijała sąsiadów', 'Przejęła władzę nad Rosją'],
    'Była coraz bardziej zależna od Rosji'),
  q(3, 'CRISIS', 'Czy Konstytucja 3 maja zakładała trójpodział władz na ustawodawczą, wykonawczą i sądowniczą?',
    ['Tak', 'Nie, łączyła je w ręku króla', 'Wprowadzała tylko jedną władzę — sądową', 'Konstytucji nigdy nie było'],
    'Tak'),

  // ───────────────────────────────────────────────────────────────────────────
  // UPRISING — Powstanie kościuszkowskie
  // ───────────────────────────────────────────────────────────────────────────

  // ── UPRISING · Level 1 (basic recall) ─────────────────────────────────────
  q(1, 'UPRISING', 'Kto stanął na czele powstania w 1794 roku?',
    ['Tadeusz Kościuszko', 'Stanisław August Poniatowski', 'Jan III Sobieski', 'Józef Piłsudski'],
    'Tadeusz Kościuszko'),
  q(1, 'UPRISING', 'W którym roku wybuchło powstanie kościuszkowskie?',
    ['1772', '1791', '1794', '1795'],
    '1794'),
  q(1, 'UPRISING', 'Jak nazywano chłopów uzbrojonych w kosy?',
    ['Husarzami', 'Pikinierami', 'Kosynierami', 'Ułanami'],
    'Kosynierami'),
  q(1, 'UPRISING', 'W którym mieście Tadeusz Kościuszko złożył uroczystą przysięgę?',
    ['W Warszawie', 'W Krakowie', 'W Poznaniu', 'W Wilnie'],
    'W Krakowie'),
  q(1, 'UPRISING', 'Pod jaką wsią doszło do zwycięskiej bitwy z Rosjanami w 1794 roku?',
    ['Pod Maciejowicami', 'Pod Grunwaldem', 'Pod Racławicami', 'Pod Chocimiem'],
    'Pod Racławicami'),
  q(1, 'UPRISING', 'Pod jaką wsią Kościuszko poniósł klęskę i dostał się do niewoli?',
    ['Pod Racławicami', 'Pod Maciejowicami', 'Pod Wiedniem', 'Pod Beresteczkiem'],
    'Pod Maciejowicami'),
  q(1, 'UPRISING', 'Z jakiej broni słynęli kosynierzy?',
    ['Z karabinu maszynowego', 'Z miecza', 'Z procy', 'Z kosy postawionej na sztorc'],
    'Z kosy postawionej na sztorc'),
  q(1, 'UPRISING', 'Jaki stopień wojskowy miał Tadeusz Kościuszko?',
    ['Generał', 'Kapral', 'Sierżant', 'Marszałek'],
    'Generał'),
  q(1, 'UPRISING', 'Czy Tadeusz Kościuszko był naczelnikiem powstania?',
    ['Tak, był jego naczelnikiem', 'Nie, był tylko zwykłym żołnierzem', 'Nie, był kucharzem armii', 'Nie, był malarzem nadwornym'],
    'Tak, był jego naczelnikiem'),
  q(1, 'UPRISING', 'Z jakiego miasta wyruszyły wojska Kościuszki na walkę?',
    ['Z Warszawy', 'Z Krakowa', 'Z Wilna', 'Ze Lwowa'],
    'Z Krakowa'),
  q(1, 'UPRISING', 'Od czyjego nazwiska pochodzi nazwa powstania kościuszkowskiego?',
    ['Od nazwiska Tadeusza Kościuszki', 'Od nazwiska Wojciecha Bartosa', 'Od nazwiska Jana Matejki', 'Od nazwiska Stanisława Augusta'],
    'Od nazwiska Tadeusza Kościuszki'),
  q(1, 'UPRISING', 'Jakie miasto na pewien czas opanowali polscy powstańcy?',
    ['Petersburg', 'Berlin', 'Wiedeń', 'Warszawę'],
    'Warszawę'),
  q(1, 'UPRISING', 'Czyje wojska dołączyły do walczących Rosjan przeciwko powstaniu?',
    ['Wojska francuskie', 'Wojska szwedzkie', 'Wojska tureckie', 'Wojska pruskie'],
    'Wojska pruskie'),
  q(1, 'UPRISING', 'Czy powstanie kościuszkowskie zakończyło się sukcesem?',
    ['Nie, zakończyło się klęską', 'Tak, Polska wygrała', 'Tak, Polska odzyskała wszystkie ziemie', 'Powstanie nigdy się nie odbyło'],
    'Nie, zakończyło się klęską'),
  q(1, 'UPRISING', 'Czy bitwa pod Racławicami była zwycięstwem Polaków?',
    ['Tak, było to zwycięstwo Polaków', 'Nie, Polacy przegrali', 'Bitwa zakończyła się remisem', 'Bitwy pod Racławicami nigdy nie było'],
    'Tak, było to zwycięstwo Polaków'),
  q(1, 'UPRISING', 'Co znaczy słowo „powstanie"?',
    ['Zbrojne wystąpienie ludności przeciwko władzy lub obcym wojskom', 'Wstanie z łóżka rano', 'Założenie nowej szkoły', 'Wybór nowego króla'],
    'Zbrojne wystąpienie ludności przeciwko władzy lub obcym wojskom'),
  q(1, 'UPRISING', 'Co składał Tadeusz Kościuszko na rynku w Krakowie?',
    ['Uroczystą przysięgę', 'Hołd pruski', 'Egzamin wojskowy', 'Wniosek do Sejmu'],
    'Uroczystą przysięgę'),
  q(1, 'UPRISING', 'W jakie chłopskie ubrania ubierali się kosynierzy?',
    ['W zbroje rycerskie', 'W mundury rosyjskie', 'W stroje szlacheckie', 'W sukmany'],
    'W sukmany',
    'Sukmany to jasne chłopskie stroje spięte pasami.'),
  q(1, 'UPRISING', 'Ilu mniej więcej żołnierzy liczyła armia Kościuszki na początku powstania?',
    ['Kilkudziesięciu', 'Kilkanaście milionów', 'Tylko stu', 'Kilka tysięcy'],
    'Kilka tysięcy'),
  q(1, 'UPRISING', 'Czy Tadeusz Kościuszko był szanowany wśród żołnierzy?',
    ['Tak, bardzo szanowany', 'Nie, żołnierze go nie znali', 'Tak, ale tylko w Rosji', 'Tak, ale tylko w Austrii'],
    'Tak, bardzo szanowany'),
  q(1, 'UPRISING', 'Z którym z zaborców Polacy walczyli pod Racławicami?',
    ['Z Rosją', 'Z Austrią', 'Z Francją', 'Ze Szwecją'],
    'Z Rosją'),
  q(1, 'UPRISING', 'W którym wieku miało miejsce powstanie kościuszkowskie?',
    ['W XVI wieku', 'W XVII wieku', 'W XVIII wieku', 'W XIX wieku'],
    'W XVIII wieku',
    '1794 r.'),

  // ── UPRISING · Level 2 (intermediate) ─────────────────────────────────────
  q(2, 'UPRISING', 'W którym roku urodził się Tadeusz Kościuszko?',
    ['1717', '1746', '1771', '1791'],
    '1746'),
  q(2, 'UPRISING', 'W którym roku zmarł Tadeusz Kościuszko?',
    ['1795', '1817', '1830', '1918'],
    '1817'),
  q(2, 'UPRISING', 'Komu Tadeusz Kościuszko przysięgał na rynku w Krakowie?',
    ['Carowi rosyjskiemu', 'Cesarzowi Austrii', 'Tylko sobie samemu', 'Całemu narodowi polskiemu'],
    'Całemu narodowi polskiemu'),
  q(2, 'UPRISING', 'Jak miał na imię chłop, który zasłynął w bitwie pod Racławicami?',
    ['Jan Kowalski', 'Stefan Czarniecki', 'Wojciech Bartos', 'Józef Piłsudski'],
    'Wojciech Bartos'),
  q(2, 'UPRISING', 'Jakie nazwisko nadano Wojciechowi Bartosowi za męstwo pod Racławicami?',
    ['Krakowski', 'Głowacki', 'Warszawski', 'Polski'],
    'Głowacki'),
  q(2, 'UPRISING', 'Co bohatersko zrobił Wojciech Bartos podczas bitwy pod Racławicami?',
    ['Zgasił lont armaty mimo ostrzału wroga', 'Złapał konia rosyjskiego generała', 'Sam zdobył całą armię rosyjską', 'Sprowadził posiłki z Krakowa'],
    'Zgasił lont armaty mimo ostrzału wroga'),
  q(2, 'UPRISING', 'Jaki stopień wojskowy otrzymał Wojciech Bartos w nagrodę?',
    ['Stopień oficerski', 'Stopień generała', 'Stopień kaprala', 'Stopień marszałka'],
    'Stopień oficerski'),
  q(2, 'UPRISING', 'Co zdobyli kosynierzy w bitwie pod Racławicami?',
    ['Armaty wroga', 'Pałac królewski', 'Skarbiec państwa', 'Statki na Morzu Bałtyckim'],
    'Armaty wroga'),
  q(2, 'UPRISING', 'Czy żołnierze rosyjscy nosili jednolite mundury?',
    ['Tak, jednolite mundury', 'Nie, każdy miał inny strój', 'Nie, walczyli w sukmanach', 'Nie, walczyli bez ubrań'],
    'Tak, jednolite mundury'),
  q(2, 'UPRISING', 'Jakim wojskiem byli żołnierze rosyjscy w bitwie pod Racławicami?',
    ['Regularnym i zdyscyplinowanym', 'Bezładnym tłumem', 'Oddziałem pirackim', 'Drużyną dziecięcą'],
    'Regularnym i zdyscyplinowanym'),
  q(2, 'UPRISING', 'Po której bitwie powstanie zaczęło rozszerzać swój zasięg?',
    ['Po bitwie pod Racławicami', 'Po bitwie pod Maciejowicami', 'Po bitwie pod Grunwaldem', 'Po bitwie pod Połtawą'],
    'Po bitwie pod Racławicami'),
  q(2, 'UPRISING', 'Z czego były zrobione kosy używane przez kosynierów?',
    ['Z metalowego ostrza, postawionego na sztorc', 'Tylko z drewna', 'Z papieru', 'Z gliny'],
    'Z metalowego ostrza, postawionego na sztorc'),
  q(2, 'UPRISING', 'Po którym rozbiorze wybuchło powstanie kościuszkowskie?',
    ['Przed wszystkimi rozbiorami', 'Po I rozbiorze', 'Po II rozbiorze', 'Po III rozbiorze'],
    'Po II rozbiorze',
    'Powstanie 1794, II rozbiór 1793.'),
  q(2, 'UPRISING', 'Komu zaprzysiężył wierność Tadeusz Kościuszko?',
    ['Tylko swojej armii', 'Całemu narodowi polskiemu', 'Tylko ambasadorowi Rosji', 'Tylko Sejmowi'],
    'Całemu narodowi polskiemu'),
  q(2, 'UPRISING', 'Z jakiego roku pochodzi obraz Wojciecha Kossaka przedstawiający przysięgę Kościuszki?',
    ['1794', '1830', '1911', '1980'],
    '1911'),
  q(2, 'UPRISING', 'Kto namalował obraz przedstawiający przysięgę Kościuszki?',
    ['Wojciech Kossak', 'Jan Matejko', 'Stanisław Wyspiański', 'Henryk Sienkiewicz'],
    'Wojciech Kossak'),
  q(2, 'UPRISING', 'W którą stronę było wymierzone ostrze kos używanych przez kosynierów?',
    ['W dół, do koszenia trawy', 'Pionowo do góry, na sztorc', 'W bok, równolegle do ziemi', 'W tył, za plecami'],
    'Pionowo do góry, na sztorc'),
  q(2, 'UPRISING', 'Po której bitwie powstańcy próbowali łączyć się z oddziałami w innych polskich miastach?',
    ['Po Racławicach', 'Po Maciejowicach', 'Po Wiedniu', 'Po Stoczku'],
    'Po Racławicach'),
  q(2, 'UPRISING', 'Czy w wojsku Kościuszki byli zwykli chłopi?',
    ['Tak, w postaci kosynierów', 'Nie, byli tylko szlachcice', 'Nie, tylko zawodowi żołnierze', 'Nie, tylko cudzoziemcy'],
    'Tak, w postaci kosynierów'),
  q(2, 'UPRISING', 'Czy Tadeusz Kościuszko walczył wcześniej z Rosjanami przed wybuchem powstania?',
    ['Tak, wsławił się już wcześniej w walce z nimi', 'Nie, było to jego pierwsze starcie', 'Tak, ale tylko jeden raz w pojedynku', 'Nie, walczył tylko z Turkami'],
    'Tak, wsławił się już wcześniej w walce z nimi'),
  q(2, 'UPRISING', 'Kim — według tekstu — byli przedstawiciele uczestniczący w przysiędze Kościuszki?',
    ['Przedstawiciele całego narodu', 'Wyłącznie carscy urzędnicy', 'Wyłącznie kupcy z Gdańska', 'Wyłącznie zakonnicy z Częstochowy'],
    'Przedstawiciele całego narodu'),
  q(2, 'UPRISING', 'W jakim roku Tadeusz Kościuszko został naczelnikiem powstania?',
    ['1791', '1793', '1794', '1795'],
    '1794'),

  // ── UPRISING · Level 3 (advanced) ─────────────────────────────────────────
  q(3, 'UPRISING', 'Czego — według tekstu przysięgi — Kościuszko nie miał używać dla niczyjego prywatnego ucisku?',
    ['Powierzonej mu władzy', 'Swojej szabli', 'Pieniędzy państwa', 'Konstytucji'],
    'Powierzonej mu władzy'),
  q(3, 'UPRISING', 'Dla czego — według przysięgi — Kościuszko miał używać władzy?',
    ['Dla całości granic, odzyskania samowładności i ugruntowania powszechnej wolności', 'Dla zdobycia majątku', 'Dla powiększenia własnej armii', 'Dla budowy nowego pałacu'],
    'Dla całości granic, odzyskania samowładności i ugruntowania powszechnej wolności'),
  q(3, 'UPRISING', 'Co znaczy słowo „samowładność" w przysiędze Kościuszki?',
    ['Niezależność', 'Brak wszelkich rządów', 'Władza tylko jednego człowieka', 'Niewola'],
    'Niezależność'),
  q(3, 'UPRISING', 'Gdzie dokładnie w Krakowie złożono przysięgę Kościuszki?',
    ['Na rynku Starego Miasta', 'Na Wawelu w komnatach królewskich', 'W Lasku Wolskim', 'Pod miastem, na otwartym polu'],
    'Na rynku Starego Miasta'),
  q(3, 'UPRISING', 'W jakim celu wojska Kościuszki wyruszyły z Krakowa?',
    ['Aby połączyć się z oddziałami powstańczymi w innych miastach', 'Aby uciec za granicę', 'Aby zaatakować Wiedeń', 'Aby ogłosić nowego króla'],
    'Aby połączyć się z oddziałami powstańczymi w innych miastach'),
  q(3, 'UPRISING', 'Co stało się z polskim wojskiem po dołączeniu wojsk pruskich do walki?',
    ['Polskie oddziały zaczęły ponosić porażki', 'Powstanie natychmiast zwyciężyło', 'Walki zostały wstrzymane', 'Prusy przeszły na stronę Polski'],
    'Polskie oddziały zaczęły ponosić porażki'),
  q(3, 'UPRISING', 'Po klęsce w której bitwie Tadeusz Kościuszko dostał się do niewoli?',
    ['Po Racławicach', 'Po Maciejowicach', 'Pod Wiedniem', 'Po Połtawie'],
    'Po Maciejowicach'),
  q(3, 'UPRISING', 'Do czyjej niewoli dostał się Tadeusz Kościuszko?',
    ['Do rosyjskiej', 'Do pruskiej', 'Do austriackiej', 'Do francuskiej'],
    'Do rosyjskiej'),
  q(3, 'UPRISING', 'Co stało się z Warszawą wkrótce po klęsce pod Maciejowicami?',
    ['Wojska rosyjskie ją zajęły', 'Stała się stolicą Prus', 'Została opuszczona przez wszystkich', 'Powstańcy utrzymali ją do końca'],
    'Wojska rosyjskie ją zajęły'),
  q(3, 'UPRISING', 'Czyja postawa przesądziła o zwycięstwie Polaków pod Racławicami?',
    ['Postawa kosynierów', 'Postawa Rosjan', 'Postawa Prusaków', 'Postawa szlachty pruskiej'],
    'Postawa kosynierów'),
  q(3, 'UPRISING', 'Czy kosynierzy byli lepiej wyposażeni niż żołnierze rosyjscy?',
    ['Nie, byli gorzej uzbrojeni', 'Tak, mieli lepszą broń', 'Mieli identyczne wyposażenie', 'Mieli lepsze armaty od Rosjan'],
    'Nie, byli gorzej uzbrojeni'),
  q(3, 'UPRISING', 'Czy Rosjanie byli lepiej wyćwiczeni niż kosynierzy?',
    ['Tak, byli lepiej wyćwiczeni', 'Nie, kosynierzy byli zawodowymi żołnierzami', 'Obie strony nie miały żadnego ćwiczenia', 'Kosynierzy ćwiczyli przez wiele lat w armii'],
    'Tak, byli lepiej wyćwiczeni'),
  q(3, 'UPRISING', 'Co — wśród oddziałów wroga — szczególnie zdobywali kosynierzy w bitwie pod Racławicami?',
    ['Armaty', 'Statki', 'Pociągi', 'Gołębie pocztowe'],
    'Armaty'),
  q(3, 'UPRISING', 'Jaką postawą wykazali się kosynierzy mimo gorszego uzbrojenia?',
    ['Odwagą i męstwem', 'Tchórzostwem', 'Niesubordynacją', 'Strachem przed walką'],
    'Odwagą i męstwem'),
  q(3, 'UPRISING', 'Co stanowiło o sile polskiej armii podczas powstania?',
    ['Połączenie regularnych żołnierzy i chłopskich kosynierów', 'Tylko jednolite oddziały zaciężne', 'Pojedynczy wojownicy bez armii', 'Same oddziały tureckie'],
    'Połączenie regularnych żołnierzy i chłopskich kosynierów'),
  q(3, 'UPRISING', 'W jakiej formie odbyło się złożenie przysięgi Kościuszki?',
    ['Uroczyście i publicznie, w obecności przedstawicieli całego narodu', 'Po cichu, w cztery oczy z królem', 'W liście wysłanym pocztą', 'Pojedynczo do każdego żołnierza osobno'],
    'Uroczyście i publicznie, w obecności przedstawicieli całego narodu'),
  q(3, 'UPRISING', 'Czy Kościuszko zobowiązał się dbać o całość granic Rzeczypospolitej?',
    ['Tak', 'Nie, chciał oddać ziemie zaborcom', 'Tylko o granicę zachodnią', 'Tylko o granicę z Austrią'],
    'Tak'),
  q(3, 'UPRISING', 'Czy przysięga Kościuszki wzywała do odzyskania samowładności (niezależności) narodu?',
    ['Tak', 'Nie, zgadzał się na utratę niepodległości', 'Mówiła tylko o pieniądzach', 'Mówiła tylko o zbiorach'],
    'Tak'),
  q(3, 'UPRISING', 'Czego, według przysięgi, miał używać Kościuszko, aby osiągnąć powszechną wolność?',
    ['Powierzonej mu władzy', 'Tylko własnych pieniędzy', 'Wyłącznie modlitwy', 'Sił obcego państwa'],
    'Powierzonej mu władzy'),
  q(3, 'UPRISING', 'W jakiej sytuacji państwowej znajdowała się Rzeczpospolita w 1794 roku, gdy wybuchło powstanie?',
    ['Państwo zmniejszone i zależne od Rosji po II rozbiorze', 'Najsilniejsze państwo Europy', 'Część cesarstwa Austrii', 'Państwo w pełni niepodległe i bogate'],
    'Państwo zmniejszone i zależne od Rosji po II rozbiorze'),
  q(3, 'UPRISING', 'W jaki sposób próbowano organizować powstanie poza Krakowem?',
    ['Przez łączenie się oddziałów z różnych części kraju', 'Przez wysłanie listów do króla Prus', 'Przez budowę pomników', 'Przez modlitwę bez działań zbrojnych'],
    'Przez łączenie się oddziałów z różnych części kraju'),
  q(3, 'UPRISING', 'Z którymi państwami w sumie walczyło polskie wojsko podczas powstania kościuszkowskiego?',
    ['Z Rosją i Prusami', 'Tylko z Austrią', 'Z Francją i Anglią', 'Z Turcją i Szwecją'],
    'Z Rosją i Prusami'),

  // ───────────────────────────────────────────────────────────────────────────
  // AFTERMATH — III rozbiór, utrata niepodległości, Panorama Racławicka
  // ───────────────────────────────────────────────────────────────────────────

  // ── AFTERMATH · Level 1 (basic recall) ────────────────────────────────────
  q(1, 'AFTERMATH', 'W którym roku miał miejsce III rozbiór Polski?',
    ['1772', '1791', '1793', '1795'],
    '1795'),
  q(1, 'AFTERMATH', 'Ile lat Polska była pod zaborami?',
    ['10 lat', '50 lat', '123 lata', '200 lat'],
    '123 lata',
    'Od 1795 do 1918 roku.'),
  q(1, 'AFTERMATH', 'Co utraciła Polska po III rozbiorze?',
    ['Niepodległość', 'Tylko jedno miasto', 'Tylko dostęp do morza', 'Pieniądze, ale nie ziemię'],
    'Niepodległość'),
  q(1, 'AFTERMATH', 'Które trzy państwa dokonały III rozbioru Polski?',
    ['Rosja, Prusy i Austria', 'Tylko Rosja i Prusy', 'Francja, Anglia i Hiszpania', 'Szwecja, Turcja i Włochy'],
    'Rosja, Prusy i Austria'),
  q(1, 'AFTERMATH', 'Co zrobił król Stanisław August Poniatowski po III rozbiorze?',
    ['Zrzekł się polskiego tronu', 'Założył nową stolicę', 'Walczył dalej w lasach', 'Został cesarzem Austrii'],
    'Zrzekł się polskiego tronu'),
  q(1, 'AFTERMATH', 'Gdzie był więziony Tadeusz Kościuszko po klęsce powstania?',
    ['W Berlinie', 'W Wiedniu', 'W Petersburgu', 'W Paryżu'],
    'W Petersburgu',
    'Petersburg był wtedy stolicą Rosji.'),
  q(1, 'AFTERMATH', 'Ile lat Tadeusz Kościuszko był więziony w Rosji?',
    ['Tylko jeden dzień', 'Dwa lata', 'Sto lat', 'Dwadzieścia lat'],
    'Dwa lata'),
  q(1, 'AFTERMATH', 'Czy Tadeusz Kościuszko wrócił do Polski po uwolnieniu z więzienia?',
    ['Nie, nigdy nie wrócił', 'Tak, od razu', 'Tak, po roku', 'Tak, ale tylko na chwilę'],
    'Nie, nigdy nie wrócił'),
  q(1, 'AFTERMATH', 'Dokąd wyjechał Kościuszko po uwolnieniu z więzienia?',
    ['Na Zachód', 'Na wschód, w głąb Rosji', 'Do Turcji', 'Do Chin'],
    'Na Zachód'),
  q(1, 'AFTERMATH', 'Jak nazywamy państwa, które dokonały rozbiorów Polski?',
    ['Sojusznicy', 'Wyzwoliciele', 'Pielgrzymi', 'Zaborcy'],
    'Zaborcy'),
  q(1, 'AFTERMATH', 'Czy Polska istniała na mapie Europy zaraz po 1795 roku?',
    ['Nie, zniknęła z mapy', 'Tak, jako Cesarstwo Polskie', 'Tak, jako Rzeczpospolita Wolnych Narodów', 'Tak, ale była mała'],
    'Nie, zniknęła z mapy'),
  q(1, 'AFTERMATH', 'Czy zaborcy ścigali przywódców powstania?',
    ['Tak, ścigali ich', 'Nie, każdy mógł odejść do domu', 'Tylko powstańców francuskich', 'Nie było żadnych przywódców'],
    'Tak, ścigali ich'),
  q(1, 'AFTERMATH', 'Z jakiej mapy zniknęła Rzeczpospolita po III rozbiorze?',
    ['Z mapy Europy', 'Tylko z mapy szkolnej', 'Tylko z mapy Wrocławia', 'Z mapy Afryki'],
    'Z mapy Europy'),
  q(1, 'AFTERMATH', 'Jak nazywa się obraz upamiętniający bitwę pod Racławicami?',
    ['Panorama Racławicka', 'Bitwa pod Grunwaldem', 'Hołd pruski', 'Stańczyk'],
    'Panorama Racławicka'),
  q(1, 'AFTERMATH', 'W którym mieście można dziś oglądać Panoramę Racławicką?',
    ['W Krakowie', 'W Warszawie', 'We Wrocławiu', 'W Gdańsku'],
    'We Wrocławiu'),
  q(1, 'AFTERMATH', 'W jakim budynku eksponowana jest Panorama Racławicka?',
    ['W rotundzie (okrągłym budynku)', 'W kościele', 'W zamku królewskim', 'Na dworcu kolejowym'],
    'W rotundzie (okrągłym budynku)'),
  q(1, 'AFTERMATH', 'Kto był jednym z głównych twórców Panoramy Racławickiej?',
    ['Jan Matejko', 'Stanisław Wyspiański', 'Józef Chełmoński', 'Jan Styka'],
    'Jan Styka'),
  q(1, 'AFTERMATH', 'Z jakiej okazji powstała Panorama Racławicka?',
    ['Setnej rocznicy zwycięstwa pod Racławicami', 'Setnej rocznicy III rozbioru', 'Założenia Wrocławia', 'Stulecia śmierci króla'],
    'Setnej rocznicy zwycięstwa pod Racławicami'),
  q(1, 'AFTERMATH', 'Ile metrów wysokości ma Panorama Racławicka?',
    ['1 metr', '15 metrów', '100 metrów', '500 metrów'],
    '15 metrów'),
  q(1, 'AFTERMATH', 'Ile mniej więcej metrów szerokości ma Panorama Racławicka?',
    ['10 metrów', '50 metrów', 'Ponad 100 metrów', '1 kilometr'],
    'Ponad 100 metrów'),
  q(1, 'AFTERMATH', 'Co znaczy „panorama" w odniesieniu do tego obrazu?',
    ['Bardzo szeroki obraz, otaczający widza', 'Bardzo mały portret', 'Rzeźba z brązu', 'Mapa Polski'],
    'Bardzo szeroki obraz, otaczający widza'),
  q(1, 'AFTERMATH', 'Czy Panorama Racławicka jest mała i mieści się w pokoju?',
    ['Nie, jest ogromna', 'Tak, można ją powiesić w pokoju', 'Tak, jest mniejsza niż książka', 'Tylko fragment jest duży'],
    'Nie, jest ogromna'),

  // ── AFTERMATH · Level 2 (intermediate) ────────────────────────────────────
  q(2, 'AFTERMATH', 'Ile było rozbiorów Polski łącznie?',
    ['Dwa', 'Trzy', 'Cztery', 'Pięć'],
    'Trzy'),
  q(2, 'AFTERMATH', 'Co spotkało wielu przywódców powstania kościuszkowskiego?',
    ['Dostali się do niewoli i wywieziono ich w głąb Rosji', 'Wszyscy uciekli do Ameryki', 'Otrzymali nagrody od cara', 'Zostali królami Prus'],
    'Dostali się do niewoli i wywieziono ich w głąb Rosji'),
  q(2, 'AFTERMATH', 'W którym mieście Rosji uwięziono Tadeusza Kościuszkę?',
    ['W Moskwie', 'W Petersburgu', 'We Władywostoku', 'W Kijowie'],
    'W Petersburgu'),
  q(2, 'AFTERMATH', 'Co oznaczała klęska powstania kościuszkowskiego dla Polaków?',
    ['Wielką tragedię i koniec niepodległości', 'Małą porażkę bez znaczenia', 'Tylko utratę kilku dział', 'Powód do świętowania'],
    'Wielką tragedię i koniec niepodległości'),
  q(2, 'AFTERMATH', 'Ilu zaborców brało udział w III rozbiorze Polski?',
    ['Tylko dwóch', 'Trzech: Rosja, Prusy i Austria', 'Czterech', 'Tylko Rosja'],
    'Trzech: Rosja, Prusy i Austria'),
  q(2, 'AFTERMATH', 'Co było bezpośrednim skutkiem klęski powstania kościuszkowskiego?',
    ['Trzeci rozbiór i koniec niepodległości', 'Powstanie wolnej Polski', 'Wojna z Anglią', 'Powrót Kościuszki na tron'],
    'Trzeci rozbiór i koniec niepodległości'),
  q(2, 'AFTERMATH', 'Kto, oprócz Jana Styki, był głównym współtwórcą Panoramy Racławickiej?',
    ['Wojciech Kossak', 'Jan Matejko', 'Tadeusz Kościuszko', 'Stanisław Wyspiański'],
    'Wojciech Kossak'),
  q(2, 'AFTERMATH', 'Skąd zbierali materiały twórcy Panoramy Racławickiej?',
    ['Odwiedzili pole bitwy i zbierali wzory broni i mundurów', 'Wszystko wymyślili sami w pracowni', 'Sięgnęli do internetu', 'Pisali do wojska rosyjskiego'],
    'Odwiedzili pole bitwy i zbierali wzory broni i mundurów'),
  q(2, 'AFTERMATH', 'Po której stronie walczyli kosynierzy?',
    ['Po polskiej', 'Po rosyjskiej', 'Po pruskiej', 'Po austriackiej'],
    'Po polskiej'),
  q(2, 'AFTERMATH', 'W jakim okresie zaborcy prowadzili rozmowy o III rozbiorze Polski?',
    ['Jeszcze w czasie trwania walk powstania', 'Sto lat po powstaniu', 'W roku 1772', 'Już w średniowieczu'],
    'Jeszcze w czasie trwania walk powstania'),
  q(2, 'AFTERMATH', 'Kto prowadził rozmowy o ostatecznym podziale ziem polskich?',
    ['Władcy Rosji, Austrii i Prus', 'Polscy biskupi', 'Sejm Rzeczypospolitej', 'Rada Regencyjna'],
    'Władcy Rosji, Austrii i Prus'),
  q(2, 'AFTERMATH', 'Z jakiej rocznicy bitwy pod Racławicami powstała Panorama?',
    ['Z setnej rocznicy zwycięstwa', 'Z dziesiątej rocznicy', 'Z piętnastej rocznicy', 'Z czterechsetnej rocznicy'],
    'Z setnej rocznicy zwycięstwa'),
  q(2, 'AFTERMATH', 'Czego doświadczali Polacy po III rozbiorze przez 123 lata?',
    ['Życia pod władzą obcych zaborców', 'Stałych zwycięstw militarnych', 'Niezakłóconej niepodległości', 'Złotego wieku rozkwitu państwa'],
    'Życia pod władzą obcych zaborców'),
  q(2, 'AFTERMATH', 'Czy Polska istniała na mapie Europy w XIX wieku jako niezależne państwo?',
    ['Nie, była podzielona między zaborców', 'Tak, jako Cesarstwo Polskie', 'Tak, jako Wielka Polska', 'Tak, jako Republika Polska'],
    'Nie, była podzielona między zaborców'),
  q(2, 'AFTERMATH', 'Po którym powstaniu Polska straciła niepodległość na 123 lata?',
    ['Po powstaniu kościuszkowskim', 'Po powstaniu listopadowym', 'Po powstaniu warszawskim', 'Po powstaniu styczniowym'],
    'Po powstaniu kościuszkowskim'),
  q(2, 'AFTERMATH', 'Czego dokonali zaborcy w 1795 roku?',
    ['Trzeciego rozbioru Polski', 'Pierwszego rozbioru Polski', 'Wprowadzenia konstytucji', 'Wybrania Kościuszki na króla'],
    'Trzeciego rozbioru Polski'),
  q(2, 'AFTERMATH', 'W jaki sposób zaborcy traktowali przywódców powstania?',
    ['Brali ich do niewoli i wywozili w głąb Rosji', 'Dawali im nagrody i medale', 'Zapraszali na przyjęcia w pałacu', 'Pozwalali im rządzić nadal'],
    'Brali ich do niewoli i wywozili w głąb Rosji'),
  q(2, 'AFTERMATH', 'Co dla zwykłego Polaka oznaczał III rozbiór?',
    ['Życie pod władzą obcego państwa zaborczego', 'Otrzymanie dużej wypłaty', 'Możliwość wyboru nowego króla', 'Brak żadnych zmian'],
    'Życie pod władzą obcego państwa zaborczego'),
  q(2, 'AFTERMATH', 'Czy Tadeusz Kościuszko wrócił do Polski po wyjściu z więzienia?',
    ['Nie, wyjechał na Zachód i nigdy nie wrócił', 'Tak, wrócił od razu', 'Tak, ale tylko po roku', 'Tak, został wojewodą krakowskim'],
    'Nie, wyjechał na Zachód i nigdy nie wrócił'),
  q(2, 'AFTERMATH', 'Co rozpoczęło się dla Polski wraz z III rozbiorem?',
    ['Trwający 123 lata okres niewoli', 'Złoty wiek bogactwa', 'Stulecie pokoju', 'Powstanie wielkiego mocarstwa'],
    'Trwający 123 lata okres niewoli'),
  q(2, 'AFTERMATH', 'Ile mniej więcej wynoszą wymiary Panoramy Racławickiej (szerokość × wysokość)?',
    ['Ponad 100 metrów × 15 metrów', '1 metr × 1 metr', '10 metrów × 10 metrów', '1000 metrów × 1000 metrów'],
    'Ponad 100 metrów × 15 metrów'),
  q(2, 'AFTERMATH', 'Ile czasu zajęło twórcom Panoramy Racławickiej przygotowanie obrazu?',
    ['Wiele miesięcy', 'Tylko jeden dzień', 'Dziesięć minut', 'Pięćset lat'],
    'Wiele miesięcy'),

  // ── AFTERMATH · Level 3 (advanced) ────────────────────────────────────────
  q(3, 'AFTERMATH', 'Co znaczy słowo „abdykacja"?',
    ['Zrzeczenie się tronu', 'Rozpoczęcie wojny', 'Mianowanie generała', 'Podpisanie pokoju'],
    'Zrzeczenie się tronu'),
  q(3, 'AFTERMATH', 'W którym państwie spędził Tadeusz Kościuszko ostatnie lata życia?',
    ['Na Zachodzie, m.in. w Szwajcarii', 'W Rosji w Petersburgu', 'W Austrii', 'W Polsce w Krakowie'],
    'Na Zachodzie, m.in. w Szwajcarii'),
  q(3, 'AFTERMATH', 'Czy Polska brała udział w decyzjach o III rozbiorze?',
    ['Nie, decydowali zaborcy bez Polski', 'Tak, na równi z innymi państwami', 'Tak, sama rozdzieliła swoje ziemie', 'Decydował Sejm we Wrocławiu'],
    'Nie, decydowali zaborcy bez Polski'),
  q(3, 'AFTERMATH', 'Co stało się z formalnym istnieniem Rzeczypospolitej po III rozbiorze?',
    ['Została zlikwidowana jako państwo', 'Istniała dalej, w zmniejszonej formie', 'Przyjęła nazwę Wielkiej Polski', 'Przeszła pod władzę Watykanu'],
    'Została zlikwidowana jako państwo'),
  q(3, 'AFTERMATH', 'Jakim państwem była Rzeczpospolita przed rozbiorami?',
    ['Niepodległym państwem polsko-litewskim', 'Częścią cesarstwa rosyjskiego', 'Prowincją Austrii', 'Republiką Niemiec'],
    'Niepodległym państwem polsko-litewskim'),
  q(3, 'AFTERMATH', 'Które miasto na wschodzie przeszło pod władzę Rosji w wyniku rozbiorów?',
    ['Wilno', 'Gdańsk', 'Toruń', 'Wrocław'],
    'Wilno'),
  q(3, 'AFTERMATH', 'Które miasto na południu przeszło pod władzę Austrii w wyniku rozbiorów?',
    ['Lwów', 'Mińsk', 'Gdańsk', 'Toruń'],
    'Lwów'),
  q(3, 'AFTERMATH', 'Które ważne miasto nadbałtyckie przeszło pod władzę Prus w wyniku rozbiorów?',
    ['Gdańsk', 'Lwów', 'Wilno', 'Mińsk'],
    'Gdańsk'),
  q(3, 'AFTERMATH', 'W którym rozbiorze Polska utraciła Warszawę?',
    ['W I rozbiorze', 'W II rozbiorze', 'W III rozbiorze', 'Nigdy nie utraciła Warszawy'],
    'W III rozbiorze'),
  q(3, 'AFTERMATH', 'W którym rozbiorze Polska utraciła Poznań?',
    ['W I rozbiorze', 'W II rozbiorze', 'W III rozbiorze', 'Nigdy nie utraciła Poznania'],
    'W II rozbiorze'),
  q(3, 'AFTERMATH', 'Które państwo zaborcze zabrało Polsce największe terytorium?',
    ['Rosja', 'Prusy', 'Austria', 'Watykan'],
    'Rosja'),
  q(3, 'AFTERMATH', 'Czy zaborcy planowali III rozbiór już w czasie trwania walk powstania?',
    ['Tak, prowadzili rozmowy w sprawie podziału jeszcze podczas walk', 'Nie, decyzję podjęli dopiero po pięćdziesięciu latach', 'Decyzję podjęto przed powstaniem', 'III rozbiór zaplanował Kościuszko'],
    'Tak, prowadzili rozmowy w sprawie podziału jeszcze podczas walk'),
  q(3, 'AFTERMATH', 'Co przedstawia scenografia w rotundzie wokół Panoramy Racławickiej?',
    ['Elementy pola bitwy', 'Salę tronową króla', 'Stolicę Polski w XX wieku', 'Pałac Stanisława Augusta'],
    'Elementy pola bitwy'),
  q(3, 'AFTERMATH', 'Jak otoczona jest osoba oglądająca Panoramę Racławicką?',
    ['Jest jakby w środku obrazu, otoczona przez dzieło i scenografię', 'Patrzy na obraz z bardzo daleka', 'Może go dotykać ręką', 'Stoi za zasłoną'],
    'Jest jakby w środku obrazu, otoczona przez dzieło i scenografię'),
  q(3, 'AFTERMATH', 'Ile lat żył Tadeusz Kościuszko?',
    ['30 lat', '50 lat', '71 lat', '100 lat'],
    '71 lat',
    '1746–1817.'),
  q(3, 'AFTERMATH', 'W którym wieku zmarł Tadeusz Kościuszko?',
    ['W XVII wieku', 'W XVIII wieku', 'W XIX wieku', 'W XX wieku'],
    'W XIX wieku',
    'Zmarł w 1817 r.'),
  q(3, 'AFTERMATH', 'W którym roku Polska odzyskała niepodległość po 123 latach zaborów?',
    ['W 1815 roku', 'W 1830 roku', 'W 1918 roku', 'W 1989 roku'],
    'W 1918 roku',
    '1795 + 123 = 1918.'),
  q(3, 'AFTERMATH', 'Jaki był los wielu polskich patriotów-przywódców po klęsce powstania?',
    ['Zostali wywiezieni w głąb Rosji', 'Otrzymali ordery od cara', 'Zostali królami Austrii', 'Założyli nowe państwo w Ameryce'],
    'Zostali wywiezieni w głąb Rosji'),
  q(3, 'AFTERMATH', 'Czy Tadeusz Kościuszko po uwolnieniu z więzienia zmarł jako człowiek wolny, poza Rosją?',
    ['Tak, zmarł na Zachodzie po zwolnieniu z więzienia', 'Nie, zmarł w więzieniu w Petersburgu', 'Nie, zginął podczas bitwy', 'Zmarł w niewoli pruskiej'],
    'Tak, zmarł na Zachodzie po zwolnieniu z więzienia'),
  q(3, 'AFTERMATH', 'Co stanowił III rozbiór dla państwa polskiego?',
    ['Ostateczny koniec niepodległości na 123 lata', 'Tylko czasowe zawieszenie władzy króla', 'Wstęp do nowej, większej Polski', 'Pomyślny układ pokojowy'],
    'Ostateczny koniec niepodległości na 123 lata'),
  q(3, 'AFTERMATH', 'Kto przyczynił się do powstania Panoramy Racławickiej, oprócz dwóch głównych malarzy?',
    ['Kilku innych malarzy współpracowało przy obrazie', 'Tylko żołnierze armii pruskiej', 'Wyłącznie dzieci ze szkoły we Wrocławiu', 'Nikt — Styka i Kossak pracowali sami w jeden dzień'],
    'Kilku innych malarzy współpracowało przy obrazie'),
  q(3, 'AFTERMATH', 'W którym stuleciu powstała Panorama Racławicka?',
    ['Pod koniec XIX wieku', 'W XVII wieku', 'W połowie XVIII wieku', 'Na początku XXI wieku'],
    'Pod koniec XIX wieku',
    'Powstała w 1894 r., na setną rocznicę bitwy.'),
];

export const kosciuszkoRozbioryBank = {
  id: 'kosciuszko-rozbiory',
  items,
};
