// AUTO-GENERATED by scripts/build-sentence-parts-bank.ts.
// Combines the original sentence-parts-level-N modules into one shared bank.
// Each item is tagged with `level` (1..8) and `topic = SENTENCE_PARTS` so
// the level-N module configs can filter their slice of the pool.
//
// Edit the source-of-truth question text by editing this file directly.

import type { ContentItem } from '../types';

export const SENTENCE_PARTS_TOPIC = 'SENTENCE_PARTS';

export const sentencePartsBank = {
  id: 'sentence-parts',
  items: [
    // ─── Level 1: Części zdania — poziom 1: Podmiot i orzeczenie ───
    {
      "id": "sentence-parts-level-1-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Pies biega po łące.'?"
        },
        "options": {
          "pl": [
            "pies",
            "biega",
            "łące",
            "po"
          ]
        },
        "answer": {
          "pl": "pies"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Dzieci śpiewają piosenkę.'?"
        },
        "options": {
          "pl": [
            "dzieci",
            "śpiewają",
            "piosenkę",
            "żadne z powyższych"
          ]
        },
        "answer": {
          "pl": "śpiewają"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Słońce świeci jasno.'?"
        },
        "options": {
          "pl": [
            "słońce",
            "świeci",
            "jasno",
            "nie ma podmiotu"
          ]
        },
        "answer": {
          "pl": "słońce"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Anna pisze list.'?"
        },
        "options": {
          "pl": [
            "Anna",
            "pisze",
            "list",
            "nie ma orzeczenia"
          ]
        },
        "answer": {
          "pl": "pisze"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Kot śpi na krześle.'?"
        },
        "options": {
          "pl": [
            "kot",
            "śpi",
            "krześle",
            "na"
          ]
        },
        "answer": {
          "pl": "kot"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Mama gotuje obiad.'?"
        },
        "options": {
          "pl": [
            "mama",
            "gotuje",
            "obiad",
            "wszystkie są orzeczeniem"
          ]
        },
        "answer": {
          "pl": "gotuje"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Ptaki fruwają po niebie.'?"
        },
        "options": {
          "pl": [
            "ptaki",
            "fruwają",
            "niebie",
            "po niebie"
          ]
        },
        "answer": {
          "pl": "ptaki"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Uczniowie czytają książkę.'?"
        },
        "options": {
          "pl": [
            "uczniowie",
            "czytają",
            "książkę",
            "uczniowie i książkę"
          ]
        },
        "answer": {
          "pl": "czytają"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Wiatr wieje mocno.'?"
        },
        "options": {
          "pl": [
            "wiatr",
            "wieje",
            "mocno",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "wiatr"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Tomek gra w piłkę.'?"
        },
        "options": {
          "pl": [
            "Tomek",
            "gra",
            "piłkę",
            "w"
          ]
        },
        "answer": {
          "pl": "gra"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Róża pachnie pięknie.'?"
        },
        "options": {
          "pl": [
            "róża",
            "pachnie",
            "pięknie",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "róża"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Chłopiec rzuca kamień.'?"
        },
        "options": {
          "pl": [
            "chłopiec",
            "rzuca",
            "kamień",
            "żadne"
          ]
        },
        "answer": {
          "pl": "rzuca"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Rzeka płynie wolno.'?"
        },
        "options": {
          "pl": [
            "rzeka",
            "płynie",
            "wolno",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "rzeka"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Babcia piecze ciasto.'?"
        },
        "options": {
          "pl": [
            "babcia",
            "piecze",
            "ciasto",
            "żadne"
          ]
        },
        "answer": {
          "pl": "piecze"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Dziewczynka tańczy na scenie.'?"
        },
        "options": {
          "pl": [
            "dziewczynka",
            "tańczy",
            "scenie",
            "na scenie"
          ]
        },
        "answer": {
          "pl": "dziewczynka"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Piotr buduje zamek.'?"
        },
        "options": {
          "pl": [
            "Piotr",
            "buduje",
            "zamek",
            "wszystkie są orzeczeniem"
          ]
        },
        "answer": {
          "pl": "buduje"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Pszczoły zbierają nektar.'?"
        },
        "options": {
          "pl": [
            "pszczoły",
            "zbierają",
            "nektar",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "pszczoły"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Nauczyciel tłumaczy lekcję.'?"
        },
        "options": {
          "pl": [
            "nauczyciel",
            "tłumaczy",
            "lekcję",
            "żadne"
          ]
        },
        "answer": {
          "pl": "tłumaczy"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Kwiat kwitnie pięknie.'?"
        },
        "options": {
          "pl": [
            "kwiat",
            "kwitnie",
            "pięknie",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "kwiat"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-1-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Kierowca prowadzi samochód.'?"
        },
        "options": {
          "pl": [
            "kierowca",
            "prowadzi",
            "samochód",
            "wszystkie są orzeczeniem"
          ]
        },
        "answer": {
          "pl": "prowadzi"
        }
      },
      "level": 1,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 2: Części zdania — poziom 2: Dopełnienie ───
    {
      "id": "sentence-parts-level-2-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Tomek pije herbatę.'?"
        },
        "options": {
          "pl": [
            "Tomek",
            "pije",
            "herbatę",
            "nie ma dopełnienia"
          ]
        },
        "answer": {
          "pl": "herbatę"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Kasia pisze list.'?"
        },
        "options": {
          "pl": [
            "Kasia",
            "pisze",
            "list",
            "żadne"
          ]
        },
        "answer": {
          "pl": "list"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Mama kocha dziecko.'?"
        },
        "options": {
          "pl": [
            "mama",
            "kocha",
            "dziecko",
            "wszystkie"
          ]
        },
        "answer": {
          "pl": "dziecko"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Paweł czyta gazetę.'?"
        },
        "options": {
          "pl": [
            "Paweł",
            "czyta",
            "gazetę",
            "nie ma podmiotu"
          ]
        },
        "answer": {
          "pl": "Paweł"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Kucharz gotuje zupę.'?"
        },
        "options": {
          "pl": [
            "kucharz",
            "gotuje",
            "zupę",
            "żadne"
          ]
        },
        "answer": {
          "pl": "zupę"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Dzieci oglądają film.'?"
        },
        "options": {
          "pl": [
            "dzieci",
            "oglądają",
            "film",
            "wszystkie"
          ]
        },
        "answer": {
          "pl": "oglądają"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Ogrodnik sadzi drzewo.'?"
        },
        "options": {
          "pl": [
            "ogrodnik",
            "sadzi",
            "drzewo",
            "żadne"
          ]
        },
        "answer": {
          "pl": "drzewo"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Michał kupuje rower.'?"
        },
        "options": {
          "pl": [
            "Michał",
            "kupuje",
            "rower",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "rower"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Nauczyciel ocenia ucznia.'?"
        },
        "options": {
          "pl": [
            "nauczyciel",
            "ocenia",
            "ucznia",
            "żadne"
          ]
        },
        "answer": {
          "pl": "ucznia"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Kot łowi mysz.'?"
        },
        "options": {
          "pl": [
            "kot",
            "łowi",
            "mysz",
            "żadne"
          ]
        },
        "answer": {
          "pl": "kot"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Kierowca prowadzi autobus.'?"
        },
        "options": {
          "pl": [
            "kierowca",
            "prowadzi",
            "autobus",
            "wszystkie"
          ]
        },
        "answer": {
          "pl": "autobus"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Lekarz bada pacjenta.'?"
        },
        "options": {
          "pl": [
            "lekarz",
            "bada",
            "pacjenta",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "pacjenta"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Pies gryzie kość.'?"
        },
        "options": {
          "pl": [
            "pies",
            "gryzie",
            "kość",
            "żadne"
          ]
        },
        "answer": {
          "pl": "gryzie"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Jan maluje obraz.'?"
        },
        "options": {
          "pl": [
            "Jan",
            "maluje",
            "obraz",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "obraz"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Ewa zamyka drzwi.'?"
        },
        "options": {
          "pl": [
            "Ewa",
            "zamyka",
            "drzwi",
            "żadne"
          ]
        },
        "answer": {
          "pl": "drzwi"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Dziecko je jabłko.'?"
        },
        "options": {
          "pl": [
            "dziecko",
            "je",
            "jabłko",
            "wszystkie"
          ]
        },
        "answer": {
          "pl": "jabłko"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Tata naprawia samochód.'?"
        },
        "options": {
          "pl": [
            "tata",
            "naprawia",
            "samochód",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "samochód"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Babcia opowiada bajkę.'?"
        },
        "options": {
          "pl": [
            "babcia",
            "opowiada",
            "bajkę",
            "żadne"
          ]
        },
        "answer": {
          "pl": "babcia"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Malarz maluje ścianę.'?"
        },
        "options": {
          "pl": [
            "malarz",
            "maluje",
            "ścianę",
            "żadne"
          ]
        },
        "answer": {
          "pl": "ścianę"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-2-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest orzeczeniem w zdaniu: 'Anna gotuje makaron.'?"
        },
        "options": {
          "pl": [
            "Anna",
            "gotuje",
            "makaron",
            "żadne"
          ]
        },
        "answer": {
          "pl": "gotuje"
        }
      },
      "level": 2,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 3: Części zdania — poziom 3: Okolicznik ───
    {
      "id": "sentence-parts-level-3-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Ania czyta książkę wieczorem.'?"
        },
        "options": {
          "pl": [
            "Ania",
            "czyta",
            "książkę",
            "wieczorem"
          ]
        },
        "answer": {
          "pl": "wieczorem"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Dzieci bawią się w ogrodzie.'?"
        },
        "options": {
          "pl": [
            "dzieci",
            "bawią się",
            "w ogrodzie",
            "żadne"
          ]
        },
        "answer": {
          "pl": "w ogrodzie"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Paweł biega szybko.'?"
        },
        "options": {
          "pl": [
            "Paweł",
            "biega",
            "szybko",
            "nie ma"
          ]
        },
        "answer": {
          "pl": "szybko"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Tata wraca jutro.'?"
        },
        "options": {
          "pl": [
            "tata",
            "wraca",
            "jutro",
            "wszystkie"
          ]
        },
        "answer": {
          "pl": "jutro"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Ptak siedzi na gałęzi.'?"
        },
        "options": {
          "pl": [
            "ptak",
            "siedzi",
            "gałęzi",
            "na gałęzi"
          ]
        },
        "answer": {
          "pl": "na gałęzi"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Wczoraj padał deszcz.'?"
        },
        "options": {
          "pl": [
            "wczoraj",
            "padał",
            "deszcz",
            "żadne"
          ]
        },
        "answer": {
          "pl": "wczoraj"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Kasia śpi w łóżku.'?"
        },
        "options": {
          "pl": [
            "Kasia",
            "śpi",
            "łóżku",
            "w łóżku"
          ]
        },
        "answer": {
          "pl": "w łóżku"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Marek jedzie do szkoły.'?"
        },
        "options": {
          "pl": [
            "Marek",
            "jedzie",
            "do szkoły",
            "szkoły"
          ]
        },
        "answer": {
          "pl": "do szkoły"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Babcia gotuje obiad w kuchni.'?"
        },
        "options": {
          "pl": [
            "babcia",
            "gotuje",
            "obiad",
            "w kuchni"
          ]
        },
        "answer": {
          "pl": "obiad"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Tomek rysuje pięknie.'?"
        },
        "options": {
          "pl": [
            "Tomek",
            "rysuje",
            "pięknie",
            "żadne"
          ]
        },
        "answer": {
          "pl": "pięknie"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Chłopiec biegnie do parku.'?"
        },
        "options": {
          "pl": [
            "chłopiec",
            "biegnie",
            "do parku",
            "żadne"
          ]
        },
        "answer": {
          "pl": "do parku"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Mama wraca z pracy.'?"
        },
        "options": {
          "pl": [
            "mama",
            "wraca",
            "z pracy",
            "pracy"
          ]
        },
        "answer": {
          "pl": "z pracy"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Dzieci śpiewają głośno.'?"
        },
        "options": {
          "pl": [
            "dzieci",
            "śpiewają",
            "głośno",
            "żadne"
          ]
        },
        "answer": {
          "pl": "głośno"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Zosia maluje obraz w pokoju.'?"
        },
        "options": {
          "pl": [
            "Zosia",
            "maluje",
            "obraz",
            "w pokoju"
          ]
        },
        "answer": {
          "pl": "obraz"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Nauczyciel mówi wyraźnie.'?"
        },
        "options": {
          "pl": [
            "nauczyciel",
            "mówi",
            "wyraźnie",
            "żadne"
          ]
        },
        "answer": {
          "pl": "wyraźnie"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Pies biega po podwórku.'?"
        },
        "options": {
          "pl": [
            "pies",
            "biega",
            "podwórku",
            "po podwórku"
          ]
        },
        "answer": {
          "pl": "po podwórku"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Samolot lata wysoko.'?"
        },
        "options": {
          "pl": [
            "samolot",
            "lata",
            "wysoko",
            "żadne"
          ]
        },
        "answer": {
          "pl": "wysoko"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Rodzice jadą na wakacje.'?"
        },
        "options": {
          "pl": [
            "rodzice",
            "jadą",
            "na wakacje",
            "żadne"
          ]
        },
        "answer": {
          "pl": "na wakacje"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Uczniowie piszą test cicho.'?"
        },
        "options": {
          "pl": [
            "uczniowie",
            "piszą",
            "test",
            "cicho"
          ]
        },
        "answer": {
          "pl": "test"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-3-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest okolicznikiem w zdaniu: 'Babcia uśmiecha się serdecznie.'?"
        },
        "options": {
          "pl": [
            "babcia",
            "uśmiecha się",
            "serdecznie",
            "żadne"
          ]
        },
        "answer": {
          "pl": "serdecznie"
        }
      },
      "level": 3,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 4: Części zdania — poziom 4: Przydawka ───
    {
      "id": "sentence-parts-level-4-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Mała dziewczynka rysuje obrazek.'?"
        },
        "options": {
          "pl": [
            "mała",
            "dziewczynka",
            "rysuje",
            "obrazek"
          ]
        },
        "answer": {
          "pl": "mała"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Czerwony samochód jedzie szybko.'?"
        },
        "options": {
          "pl": [
            "czerwony",
            "samochód",
            "jedzie",
            "szybko"
          ]
        },
        "answer": {
          "pl": "czerwony"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Wysokie drzewo rośnie w lesie.'?"
        },
        "options": {
          "pl": [
            "wysokie",
            "drzewo",
            "rośnie",
            "lesie"
          ]
        },
        "answer": {
          "pl": "wysokie"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Nowa książka leży na stole.'?"
        },
        "options": {
          "pl": [
            "nowa",
            "książka",
            "leży",
            "stole"
          ]
        },
        "answer": {
          "pl": "nowa"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Pies śpi pod zielonym drzewem.'?"
        },
        "options": {
          "pl": [
            "pies",
            "śpi",
            "zielonym",
            "drzewem"
          ]
        },
        "answer": {
          "pl": "zielonym"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest dopełnieniem w zdaniu: 'Dzieci piją mleko.'?"
        },
        "options": {
          "pl": [
            "dzieci",
            "piją",
            "mleko",
            "żadne"
          ]
        },
        "answer": {
          "pl": "mleko"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Mądra kobieta napisała list.'?"
        },
        "options": {
          "pl": [
            "mądra",
            "kobieta",
            "napisała",
            "list"
          ]
        },
        "answer": {
          "pl": "mądra"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Stary dom stoi przy drodze.'?"
        },
        "options": {
          "pl": [
            "stary",
            "dom",
            "stoi",
            "drodze"
          ]
        },
        "answer": {
          "pl": "stary"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Ania czyta ciekawą książkę.'?"
        },
        "options": {
          "pl": [
            "Ania",
            "czyta",
            "ciekawą",
            "książkę"
          ]
        },
        "answer": {
          "pl": "ciekawą"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Babcia piecze smaczne ciasto.'?"
        },
        "options": {
          "pl": [
            "babcia",
            "piecze",
            "smaczne",
            "ciasto"
          ]
        },
        "answer": {
          "pl": "smaczne"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Gruby kot śpi na fotelu.'?"
        },
        "options": {
          "pl": [
            "gruby",
            "kot",
            "śpi",
            "fotelu"
          ]
        },
        "answer": {
          "pl": "gruby"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Chłopiec rysuje kolorowy obrazek.'?"
        },
        "options": {
          "pl": [
            "chłopiec",
            "rysuje",
            "kolorowy",
            "obrazek"
          ]
        },
        "answer": {
          "pl": "kolorowy"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Co jest okolicznikiem w zdaniu: 'Piotr wraca ze szkoły.'?"
        },
        "options": {
          "pl": [
            "Piotr",
            "wraca",
            "ze szkoły",
            "szkoły"
          ]
        },
        "answer": {
          "pl": "ze szkoły"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Ładna dziewczyna śpiewa piosenkę.'?"
        },
        "options": {
          "pl": [
            "ładna",
            "dziewczyna",
            "śpiewa",
            "piosenkę"
          ]
        },
        "answer": {
          "pl": "ładna"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Mama gotuje pyszną zupę.'?"
        },
        "options": {
          "pl": [
            "mama",
            "gotuje",
            "pyszną",
            "zupę"
          ]
        },
        "answer": {
          "pl": "pyszną"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Tomek rzuca okrągłą piłkę.'?"
        },
        "options": {
          "pl": [
            "Tomek",
            "rzuca",
            "okrągłą",
            "piłkę"
          ]
        },
        "answer": {
          "pl": "okrągłą"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Drobny deszcz pada od rana.'?"
        },
        "options": {
          "pl": [
            "drobny",
            "deszcz",
            "pada",
            "od rana"
          ]
        },
        "answer": {
          "pl": "drobny"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest podmiotem w zdaniu: 'Biały kot pije mleko.'?"
        },
        "options": {
          "pl": [
            "biały",
            "kot",
            "pije",
            "mleko"
          ]
        },
        "answer": {
          "pl": "kot"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Nasz pies biegnie szybko.'?"
        },
        "options": {
          "pl": [
            "nasz",
            "pies",
            "biegnie",
            "szybko"
          ]
        },
        "answer": {
          "pl": "nasz"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-4-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które słowo jest przydawką w zdaniu: 'Młody nauczyciel pisze lekcję.'?"
        },
        "options": {
          "pl": [
            "młody",
            "nauczyciel",
            "pisze",
            "lekcję"
          ]
        },
        "answer": {
          "pl": "młody"
        }
      },
      "level": 4,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 5: Części zdania — poziom 5: Wszystkie 5 części — utrwalenie ───
    {
      "id": "sentence-parts-level-5-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Mała Ania czyta ciekawą książkę w parku.' czym jest słowo 'mała'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Wczoraj nauczyciel tłumaczył nową lekcję.' czym jest słowo 'wczoraj'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "okolicznikiem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Tata kupił synowi nowy rower.' czym jest słowo 'tata'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "podmiotem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Stary dziadek opowiadał wnukom bajki.' czym jest słowo 'opowiadał'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "orzeczeniem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Rano babcia piekła smaczne ciasto.' czym jest słowo 'smaczne'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Piękne kwiaty rosną w ogrodzie.' czym jest wyrażenie 'w ogrodzie'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "okolicznikiem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Młoda dziewczynka szyła sukienkę dla lalki.' czym jest słowo 'sukienkę'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "dopełnieniem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Mądry uczeń rozwiązał trudne zadanie szybko.' czym jest słowo 'szybko'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "okolicznikiem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Wczoraj mój brat zbudował wielki zamek z piasku.' czym jest słowo 'wielki'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Rano pies biegał po zielonej łące.' czym jest słowo 'pies'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "podmiotem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Mama gotuje pyszną zupę w kuchni.' czym jest słowo 'zupę'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "dopełnieniem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Duży pies gonił przestraszonego kota.' czym jest słowo 'duży'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Ania napisała długi list do babci.' czym jest słowo 'napisała'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "orzeczeniem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Gruby kot pił białe mleko z miski.' czym jest wyrażenie 'z miski'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "przydawką",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Młodzi uczniowie czytali ciekawą historię wieczorem.' czym jest słowo 'wieczorem'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "przydawką",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Słodkie jabłka rosną na wysokich drzewach.' czym jest słowo 'słodkie'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Tomek jeździł na rowerze po parku.' czym jest wyrażenie 'po parku'?"
        },
        "options": {
          "pl": [
            "dopełnieniem",
            "podmiotem",
            "orzeczeniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Zmęczona mama piła gorącą kawę wieczorem.' czym jest słowo 'kawę'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "dopełnieniem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Mały chłopiec rzucił piłkę daleko.' czym jest słowo 'daleko'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "okolicznikiem"
          ]
        },
        "answer": {
          "pl": "okolicznikiem"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-5-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Nasza babcia piecze pyszne ciasto na niedzielę.' czym jest słowo 'nasza'?"
        },
        "options": {
          "pl": [
            "podmiotem",
            "orzeczeniem",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 5,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 6: Części zdania — poziom 6: Pytania pomocnicze ───
    {
      "id": "sentence-parts-level-6-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytania odpowiada podmiot?"
        },
        "options": {
          "pl": [
            "kto? co?",
            "co robi? co się z nim dzieje?",
            "jaki? który? czyj?",
            "gdzie? kiedy? jak?"
          ]
        },
        "answer": {
          "pl": "kto? co?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytania odpowiada orzeczenie?"
        },
        "options": {
          "pl": [
            "kto? co?",
            "co robi? co się z nim dzieje?",
            "jaki? który? czyj?",
            "kogo? czego?"
          ]
        },
        "answer": {
          "pl": "co robi? co się z nim dzieje?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytania odpowiada przydawka?"
        },
        "options": {
          "pl": [
            "kto? co?",
            "co robi?",
            "jaki? który? czyj? ile?",
            "gdzie? kiedy? jak?"
          ]
        },
        "answer": {
          "pl": "jaki? który? czyj? ile?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytania odpowiada okolicznik?"
        },
        "options": {
          "pl": [
            "kto? co?",
            "co robi?",
            "jaki? który?",
            "gdzie? kiedy? jak? dlaczego?"
          ]
        },
        "answer": {
          "pl": "gdzie? kiedy? jak? dlaczego?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Które pytania to typowe pytania dopełnienia?"
        },
        "options": {
          "pl": [
            "kto? co?",
            "kogo? czego? komu? czemu?",
            "jaki? który?",
            "gdzie? kiedy?"
          ]
        },
        "answer": {
          "pl": "kogo? czego? komu? czemu?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'szybko' w zdaniu 'Ania biegnie szybko.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co robi?",
            "jak?",
            "jaki?"
          ]
        },
        "answer": {
          "pl": "jak?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'wczoraj' w zdaniu 'Wczoraj padał deszcz.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co?",
            "kiedy?",
            "dlaczego?"
          ]
        },
        "answer": {
          "pl": "kiedy?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'czerwony' w zdaniu 'Czerwony samochód stoi.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co robi?",
            "gdzie?",
            "jaki?"
          ]
        },
        "answer": {
          "pl": "jaki?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'list' w zdaniu 'Ania pisze list.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co?",
            "jak?",
            "gdzie?"
          ]
        },
        "answer": {
          "pl": "co?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada wyrażenie 'w parku' w zdaniu 'Dzieci bawią się w parku.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co robi?",
            "gdzie?",
            "jak?"
          ]
        },
        "answer": {
          "pl": "gdzie?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo, które odpowiada na pytanie 'kto?' lub 'co?', to najczęściej:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "przydawka",
            "okolicznik"
          ]
        },
        "answer": {
          "pl": "podmiot"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo, które odpowiada na pytanie 'jaki?', to:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "przydawka",
            "okolicznik"
          ]
        },
        "answer": {
          "pl": "przydawka"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo, które odpowiada na pytanie 'dlaczego?', to:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "dopełnienie",
            "okolicznik"
          ]
        },
        "answer": {
          "pl": "okolicznik"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo, które odpowiada na pytanie 'co robi?', to:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "przydawka",
            "dopełnienie"
          ]
        },
        "answer": {
          "pl": "orzeczenie"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo odpowiadające na pytania 'kogo? czego? komu?' (inne niż podmiot) to:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "dopełnienie",
            "okolicznik"
          ]
        },
        "answer": {
          "pl": "dopełnienie"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada wyrażenie 'z powodu bólu' w zdaniu 'Została w domu z powodu bólu.'?"
        },
        "options": {
          "pl": [
            "kiedy?",
            "gdzie?",
            "dlaczego?",
            "jak?"
          ]
        },
        "answer": {
          "pl": "dlaczego?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'dwie' w zdaniu 'Dwie dziewczynki tańczą.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co robi?",
            "ile?",
            "jak?"
          ]
        },
        "answer": {
          "pl": "ile?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'mojego' w zdaniu 'To jest dom mojego brata.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co robi?",
            "gdzie?",
            "czyj?"
          ]
        },
        "answer": {
          "pl": "czyj?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo, które odpowiada na pytanie 'gdzie?', to:"
        },
        "options": {
          "pl": [
            "podmiot",
            "orzeczenie",
            "dopełnienie",
            "okolicznik"
          ]
        },
        "answer": {
          "pl": "okolicznik"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-6-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Na jakie pytanie odpowiada słowo 'siostrze' w zdaniu 'Dał siostrze prezent.'?"
        },
        "options": {
          "pl": [
            "kto?",
            "co?",
            "komu?",
            "jaki?"
          ]
        },
        "answer": {
          "pl": "komu?"
        }
      },
      "level": 6,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 7: Części zdania — poziom 7: Rodzaje okolicznika i przydawki ───
    {
      "id": "sentence-parts-level-7-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'w parku' w zdaniu 'Dzieci bawią się w parku.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "miejsca"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'wczoraj' w zdaniu 'Wczoraj padał deszcz.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "przyczyny"
          ]
        },
        "answer": {
          "pl": "czasu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'szybko' w zdaniu 'Ania biegnie szybko.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "sposobu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'z powodu deszczu' w zdaniu 'Został w domu z powodu deszczu.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "przyczyny"
          ]
        },
        "answer": {
          "pl": "przyczyny"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'po zakupy' w zdaniu 'Poszła do sklepu po zakupy.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "celu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'w lesie' w zdaniu 'Grzyby rosną w lesie.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "miejsca"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'rano' w zdaniu 'Rano pije kawę.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "czasu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'cicho' w zdaniu 'Mówił cicho.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "celu"
          ]
        },
        "answer": {
          "pl": "sposobu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'z powodu choroby' w zdaniu 'Nie przyszedł z powodu choroby.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "przyczyny",
            "celu"
          ]
        },
        "answer": {
          "pl": "przyczyny"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wyrażenie 'po chleb' w zdaniu 'Idę do sklepu po chleb.' to okolicznik..."
        },
        "options": {
          "pl": [
            "miejsca",
            "czasu",
            "celu",
            "sposobu"
          ]
        },
        "answer": {
          "pl": "celu"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'czerwony' w zdaniu 'Czerwony samochód jedzie.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "przymiotna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'brata' w zdaniu 'To jest książka brata.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "rzeczowna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'trzy' w zdaniu 'Trzy koty siedzą na płocie.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "liczebna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'moja' w zdaniu 'Moja siostra gra na pianinie.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "zaimkowa"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'zielone' w zdaniu 'Zielone liście spadają.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "przymiotna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'pięciu' w zdaniu 'Pięciu chłopców gra w piłkę.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "liczebna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'mamy' w zdaniu 'To jest torebka mamy.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "rzeczowna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'twój' w zdaniu 'Twój pies szczeka.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "zaimkowa"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'bardzo' w zdaniu 'Jest bardzo wysoki.' to okolicznik..."
        },
        "options": {
          "pl": [
            "czasu",
            "miejsca",
            "sposobu",
            "stopnia"
          ]
        },
        "answer": {
          "pl": "stopnia"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-7-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Słowo 'piękne' w zdaniu 'Piękne kwiaty pachną.' to przydawka..."
        },
        "options": {
          "pl": [
            "przymiotna",
            "rzeczowna",
            "liczebna",
            "zaimkowa"
          ]
        },
        "answer": {
          "pl": "przymiotna"
        }
      },
      "level": 7,
      "topic": "SENTENCE_PARTS"
    },
    // ─── Level 8: Części zdania — poziom 8: Zdania złożone i trudne przypadki ───
    {
      "id": "sentence-parts-level-8-01",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Jutro będziemy musieli pójść do lekarza.' orzeczenie 'będziemy musieli pójść' to orzeczenie..."
        },
        "options": {
          "pl": [
            "proste",
            "złożone imienne",
            "złożone modalne",
            "złożone fazowe"
          ]
        },
        "answer": {
          "pl": "złożone modalne"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-02",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Ania jest nauczycielką.' orzeczenie 'jest nauczycielką' to orzeczenie..."
        },
        "options": {
          "pl": [
            "proste",
            "złożone imienne",
            "złożone modalne",
            "złożone fazowe"
          ]
        },
        "answer": {
          "pl": "złożone imienne"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-03",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Zaczął pisać list.' orzeczenie 'zaczął pisać' to orzeczenie..."
        },
        "options": {
          "pl": [
            "proste",
            "złożone imienne",
            "złożone modalne",
            "złożone fazowe"
          ]
        },
        "answer": {
          "pl": "złożone fazowe"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-04",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Idę do szkoły.' podmiot jest..."
        },
        "options": {
          "pl": [
            "gramatyczny",
            "logiczny",
            "domyślny (ukryty)",
            "szeregowy"
          ]
        },
        "answer": {
          "pl": "domyślny (ukryty)"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-05",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Ania i Kasia bawią się razem.' podmiot 'Ania i Kasia' to podmiot..."
        },
        "options": {
          "pl": [
            "gramatyczny",
            "logiczny",
            "domyślny",
            "szeregowy"
          ]
        },
        "answer": {
          "pl": "szeregowy"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-06",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Brakuje mi czasu.' podmiot 'czasu' to podmiot..."
        },
        "options": {
          "pl": [
            "gramatyczny",
            "logiczny (dopełniaczowy)",
            "domyślny",
            "szeregowy"
          ]
        },
        "answer": {
          "pl": "logiczny (dopełniaczowy)"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-07",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Pisze list.' dopełnienie 'list' to dopełnienie..."
        },
        "options": {
          "pl": [
            "bliższe",
            "dalsze",
            "przydawkowe",
            "okoliczne"
          ]
        },
        "answer": {
          "pl": "bliższe"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-08",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Dałem bratu prezent.' dopełnienie 'bratu' to dopełnienie..."
        },
        "options": {
          "pl": [
            "bliższe",
            "dalsze",
            "przydawkowe",
            "okoliczne"
          ]
        },
        "answer": {
          "pl": "dalsze"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-09",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Nie lubię kawy.' dopełnienie 'kawy' to..."
        },
        "options": {
          "pl": [
            "bliższe (dopełniacz w przeczeniu)",
            "dalsze",
            "okolicznik",
            "przydawka"
          ]
        },
        "answer": {
          "pl": "bliższe (dopełniacz w przeczeniu)"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-10",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wskaż zdanie z podmiotem domyślnym:"
        },
        "options": {
          "pl": [
            "Ania czyta książkę.",
            "Pisze list do babci.",
            "Mój brat śpi.",
            "Dzieci bawią się."
          ]
        },
        "answer": {
          "pl": "Pisze list do babci."
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-11",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wskaż zdanie z orzeczeniem imiennym:"
        },
        "options": {
          "pl": [
            "Biegnie szybko.",
            "Zaczął pisać.",
            "Jest lekarzem.",
            "Musi iść."
          ]
        },
        "answer": {
          "pl": "Jest lekarzem."
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-12",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "Wskaż zdanie z orzeczeniem modalnym:"
        },
        "options": {
          "pl": [
            "Pływa dobrze.",
            "Kończy pracę.",
            "Musi się uczyć.",
            "Jest miły."
          ]
        },
        "answer": {
          "pl": "Musi się uczyć."
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-13",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Bardzo miły starszy pan rozmawiał z sąsiadem.' słowo 'starszy' jest..."
        },
        "options": {
          "pl": [
            "podmiotem",
            "okolicznikiem",
            "przydawką",
            "dopełnieniem"
          ]
        },
        "answer": {
          "pl": "przydawką"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-14",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Wczoraj wieczorem poszliśmy do kina.' drugim okolicznikiem czasu (obok 'wczoraj') jest:"
        },
        "options": {
          "pl": [
            "wieczorem",
            "do kina",
            "poszliśmy",
            "nie ma drugiego okolicznika czasu"
          ]
        },
        "answer": {
          "pl": "wieczorem"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-15",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Zawsze chce pić po meczu.' 'chce pić' to orzeczenie..."
        },
        "options": {
          "pl": [
            "proste",
            "złożone imienne",
            "złożone modalne",
            "złożone fazowe"
          ]
        },
        "answer": {
          "pl": "złożone modalne"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-16",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Mój starszy brat był kiedyś doskonałym sportowcem.' słowo 'sportowcem' jest..."
        },
        "options": {
          "pl": [
            "podmiotem",
            "częścią orzeczenia imiennego",
            "dopełnieniem",
            "przydawką"
          ]
        },
        "answer": {
          "pl": "częścią orzeczenia imiennego"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-17",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Zakończyła czytać książkę.' 'zakończyła czytać' to orzeczenie..."
        },
        "options": {
          "pl": [
            "proste",
            "złożone imienne",
            "złożone modalne",
            "złożone fazowe"
          ]
        },
        "answer": {
          "pl": "złożone fazowe"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-18",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Ania dała siostrze książkę.' słowo 'siostrze' jest dopełnieniem..."
        },
        "options": {
          "pl": [
            "bliższym",
            "dalszym",
            "okolicznym",
            "przydawkowym"
          ]
        },
        "answer": {
          "pl": "dalszym"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-19",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Piją kawę.' podmiot jest..."
        },
        "options": {
          "pl": [
            "gramatyczny ('kawę')",
            "logiczny",
            "domyślny",
            "szeregowy"
          ]
        },
        "answer": {
          "pl": "domyślny"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
    {
      "id": "sentence-parts-level-8-20",
      "type": "SINGLE_CHOICE",
      "content": {
        "prompt": {
          "pl": "W zdaniu 'Nie widziałem filmu.' słowo 'filmu' jest dopełnieniem..."
        },
        "options": {
          "pl": [
            "bliższym (dopełniacz w przeczeniu)",
            "dalszym",
            "okolicznym",
            "przydawkowym"
          ]
        },
        "answer": {
          "pl": "bliższym (dopełniacz w przeczeniu)"
        }
      },
      "level": 8,
      "topic": "SENTENCE_PARTS"
    },
  ] satisfies ContentItem[],
};

export const sentencePartsLevelTitles: Record<number, { pl: string }> = {
  1: {"pl":"Poziom 1: Podmiot i orzeczenie"},
  2: {"pl":"Poziom 2: Dopełnienie"},
  3: {"pl":"Poziom 3: Okolicznik"},
  4: {"pl":"Poziom 4: Przydawka"},
  5: {"pl":"Poziom 5: Wszystkie 5 części — utrwalenie"},
  6: {"pl":"Poziom 6: Pytania pomocnicze"},
  7: {"pl":"Poziom 7: Rodzaje okolicznika i przydawki"},
  8: {"pl":"Poziom 8: Zdania złożone i trudne przypadki"},
};

export const sentencePartsLevelDescriptions: Record<
  number,
  { pl: string }
> = {
  1: {"pl":"Rozpoznawanie podmiotu i orzeczenia w prostych zdaniach"},
  2: {"pl":"Do podmiotu i orzeczenia dochodzi dopełnienie — na co pada czynność"},
  3: {"pl":"Do znanych części dochodzi okolicznik — gdzie, kiedy, jak, dlaczego"},
  4: {"pl":"Ostatnia z pięciu części — przydawka określa rzeczownik (jaki? który? czyj?)"},
  5: {"pl":"Różne zdania — każde słowo może być dowolną częścią zdania"},
  6: {"pl":"Dopasowanie części zdania do pytań, na które odpowiada"},
  7: {"pl":"Okolicznik miejsca / czasu / sposobu / przyczyny / celu / stopnia; przydawka przymiotna / rzeczowna / liczebna / zaimkowa"},
  8: {"pl":"Orzeczenie złożone (imienne, modalne, fazowe), podmiot domyślny i szeregowy, dopełnienie bliższe vs dalsze"},
};
